config/routes.rb
Rails.application.routes.draw do
  root to: 'libraries#index'
  resources :libraries
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :library
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_one :address, dependent: :destroy

  accepts_nested_attributes_for :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[show edit update destroy]

  def index
    @libraries = Library.all
  end

  def new
    @library = Library.new
    @library.address = Address.new
  end

  def create
    @library = Library.new(library_params)
    if @library.save
      redirect_to library_url(@library.id)
    else
      redirect_to libraries_url
    end
  end

  def update
    if @library.update(library_params)
      redirect_to library_url(@library.id)
    else
      redirect_to libraries_url
    end
  end

  def destroy
    if @library.destroy
      redirect_to libraries_url
    else
      redirect_to library_url(@library.id)
    end
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end

  def library_params
    params.require(:library).permit(:name, address_attributes: %i[id street building])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/_form.html.erb
<%= form_for @library, html: { multipart: true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.fields_for :address do |address_form| %>
    <%= address_form.label :street %>
    <%= address_form.text_field :street %>

    <%= address_form.label :building %>
    <%= address_form.text_field :building %>
  <% end %>

  <%= f.submit (@library.new_record? ? 'Create' : 'Update') %>
  <%= link_to 'Cancel', libraries_path %>
<% end %>

app/views/libraries/edit.html.erb
<h1>Edit Library</h1>
<%= render 'form' %>

app/views/libraries/index.html.erb
<h1>Libraries</h1>
<%= link_to 'New Library', new_library_path %>

<% @libraries.each do |library| %>
  <h2><%= library.name %></h2>
  <p><%= link_to 'show', library_path(library) %></p>
  <p><%= link_to 'Edit', edit_library_path(library) %></p>
<% end %>

app/views/libraries/new.html.erb
<h1>New Library</h1>
<%= render 'form' %>

app/views/libraries/show.html.erb
<h1>Library</h1>
<p><%= link_to 'Main page', libraries_path %></p>
<h2><%= @library.name %></h2>
<% if @library.address %>
  <div>
    <h3>Address:</h3>
    <% address = @library.address %>
    <%= address.street + ' ' + address.building.to_s %>
  </div>
<% end %>
<p><%= link_to 'Delete', library_path(@library), method: :delete, data: { confirm: 'Are you sure?' } %></p>